# Generated by Django 4.2.27 on 2026-02-03 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('priority', models.CharField(choices=[('NEED', 'Besoin'), ('WANT', 'Envie'), ('LUXURY', 'Luxe')], default='WANT', max_length=10)),
                ('desired_date', models.DateField(blank=True, null=True)),
                ('decision', models.CharField(choices=[('BUY_NOW', 'Acheter maintenant'), ('WAIT', 'Attendre'), ('NOT_POSSIBLE', 'Non possible')], max_length=15)),
                ('estimated_months', models.PositiveIntegerField(default=0)),
                ('recommended_monthly_saving', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_simulations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
