# Generated by Django 4.2.27 on 2026-02-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_purchasesimulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialprofile',
            name='depenses_fixes',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
