# Generated by Django 4.2.27 on 2026-02-10 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_financialprofile_depenses_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialprofile',
            name='age',
            field=models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='financialprofile',
            name='statut',
            field=models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('SALARIE', 'Salarié'), ('RETRAITE', 'Retraité')], default='ETUDIANT', max_length=10),
        ),
    ]
