# Generated by Django 4.2.27 on 2026-02-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='uniq_category_per_user',
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('SUBSCRIPTION', 'Abonnement')], default='NORMAL', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'type'), name='uniq_category_per_user_name_type'),
        ),
    ]
