# Generated by Django 4.2.27 on 2026-02-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_remove_category_uniq_category_per_user_category_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='active',
        ),
    ]
