# Generated by Django 4.2.27 on 2026-02-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_remove_category_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasesimulation',
            name='desired_date',
        ),
    ]
